/** Single-execution RPC result shaping for PostgREST-compatible functions. */
import type { Filter,FilterOperator,ParsedQuery } from './parser.js';
import type { RoutineInfo } from './routines.js';
export interface RpcQueryOptions { schema?:string;maxLimit?:number;defaultLimit?:number; }
export interface BuiltRpcEnvelope { sql:string;params:unknown[]; }
export interface RpcEnvelope { rows:Record<string,unknown>[];count:number;affected:number; }
export interface GetRpcPartition { args:Record<string,string>;resultParams:URLSearchParams;candidateArgNames:string[]; }
const OP:Partial<Record<FilterOperator,string>>={eq:'=',neq:'<>',gt:'>',gte:'>=',lt:'<',lte:'<=',like:'LIKE',ilike:'ILIKE',match:'~',imatch:'~*',isdistinct:'IS DISTINCT FROM',cs:'@>',cd:'<@',ov:'&&',sl:'<<',sr:'>>',nxl:'&>',nxr:'&<',adj:'-|-' };
const FTS:Partial<Record<FilterOperator,string>>={fts:'to_tsquery',plfts:'plainto_tsquery',phfts:'phraseto_tsquery',wfts:'websearch_to_tsquery'};
const FILTER_PREFIX=/^(?:not\.)?(?:eq|neq|gt|gte|lt|lte|like|ilike|match|imatch|is|isdistinct|in|cs|cd|ov|sl|sr|nxl|nxr|adj|fts|plfts|phfts|wfts)(?:\([^)]*\))?\./i;
const RESULT_KEYS=new Set(['select','order','limit','offset','or','and']);
const q=(value:string)=>`"${value.replace(/"/g,'""')}"`;
const lit=(value:string)=>`'${value.replace(/'/g,"''")}'`;
function fieldExpr(column:string):string{const parts=column.split(/(->>|->)/),base=(parts.shift()??column).trim();let sql=q(base);for(let i=0;i<parts.length;i+=2){const op=parts[i],operand=parts[i+1]?.trim();if(!op||!operand)continue;sql+=/^-?\d+$/.test(operand)?`${op}${operand}`:`${op}${lit(operand)}`;}return sql;}
function splitRpcProjection(raw:string):{alias?:string;expression:string;cast?:string}{let alias:string|undefined;let expression=raw.trim();for(let i=0;i<expression.length;i++){if(expression[i]!==':')continue;if(expression[i-1]===':'||expression[i+1]===':')continue;alias=expression.slice(0,i);expression=expression.slice(i+1);break;}const castAt=expression.lastIndexOf('::');let cast:string|undefined;if(castAt>=0){cast=expression.slice(castAt+2).trim();expression=expression.slice(0,castAt);if(!/^[A-Za-z0-9_$ ]+$/.test(cast))throw new Error(`Invalid RPC select cast: ${raw}`);}return{...(alias&&{alias}),expression,...(cast&&{cast})};}
function rpcProjectionOutputName(expression:string):string{const parts=expression.split(/->>|->/).map(x=>x.trim()).filter(Boolean);for(let i=parts.length-1;i>=1;i--)if(!/^-?\d+$/.test(parts[i]!))return parts[i]!;return parts[0]??expression;}
function rpcProjection(raw:string):string{const{alias,expression,cast}=splitRpcProjection(raw);let sql=fieldExpr(expression);if(cast)sql=`CAST(${sql} AS ${cast})`;const output=alias??rpcProjectionOutputName(expression);return `${sql} AS ${q(output)}`;}
export function partitionGetRpcParams(params:URLSearchParams,routine?:RoutineInfo):GetRpcPartition{const args:Record<string,string>={},resultParams=new URLSearchParams(),candidateArgNames:string[]=[];for(const[key,value]of params.entries()){const isModifier=RESULT_KEYS.has(key),looksFilter=FILTER_PREFIX.test(value);if(!isModifier&&!looksFilter)candidateArgNames.push(key);if(routine&&!isModifier&&!looksFilter&&routine.argNames.includes(key))args[key]=value;else resultParams.append(key,value);}return{args,resultParams,candidateArgNames};}
export function buildRpcEnvelopeQuery(functionName:string,args:Record<string,unknown>,query:ParsedQuery,options:RpcQueryOptions={}):BuiltRpcEnvelope{const params:unknown[]=[];const add=(value:unknown)=>{params.push(value);return'$' + params.length;};const schemaPrefix=options.schema?`${q(options.schema)}.`:'';const argSql=Object.keys(args).map(name=>`${q(name)} => ${add(args[name])}`).join(', ');const where=buildWhere(query.filters,add);const order=query.order.length?` ORDER BY ${query.order.map(item=>`${fieldExpr(item.column)} ${item.direction.toUpperCase()}${item.nullsFirst===undefined?'':item.nullsFirst?' NULLS FIRST':' NULLS LAST'}`).join(', ')}`:'';let limit=query.limit??options.defaultLimit;if(limit!==undefined&&options.maxLimit!==undefined)limit=Math.min(limit,options.maxLimit);const page=`${limit!==undefined?` LIMIT ${limit}`:''}${query.offset!==undefined&&query.offset>0?` OFFSET ${query.offset}`:''}`;const columns=query.columns==='*'?'*':query.columns.map(rpcProjection).join(', ');const sql=`WITH "__pgrst_rpc" AS MATERIALIZED (\n  SELECT * FROM ${schemaPrefix}${q(functionName)}(${argSql})\n),\n"__pgrst_filtered" AS MATERIALIZED (\n  SELECT * FROM "__pgrst_rpc"${where?` WHERE ${where}`:''}\n),\n"__pgrst_page" AS (\n  SELECT ${columns} FROM "__pgrst_filtered"${order}${page}\n)\nSELECT\n  COALESCE((SELECT json_agg(row_to_json("__pgrst_page")) FROM "__pgrst_page"), '[]'::json) AS "__pgrst_rows",\n  (SELECT COUNT(*) FROM "__pgrst_filtered")::bigint AS "__pgrst_count",\n  (SELECT COUNT(*) FROM "__pgrst_rpc")::bigint AS "__pgrst_affected"`;return{sql,params};}
function buildWhere(filters:Filter[],add:(value:unknown)=>string):string{return filters.map(filter=>condition(filter,add)).filter(Boolean).join(' AND ');}
function condition(filter:Filter,add:(value:unknown)=>string):string{const{column,operator,value,negate,config,quantifier}=filter;if(operator==='or'||operator==='and'){const joiner=operator==='or'?' OR ':' AND ',inner=(value as Filter[]).map(item=>condition(item,add)).filter(Boolean).join(joiner);return negate?`NOT ((${inner}))`:`(${inner})`;}const field=fieldExpr(column);let result:string;if(operator==='is')result=value===null?`${field} IS NULL`:value===true?`${field} IS TRUE`:value===false?`${field} IS FALSE`:value==='not_null'?`${field} IS NOT NULL`:value==='unknown'?`${field} IS UNKNOWN`:`${field} IS ${add(value)}`;else if(operator==='isdistinct')result=`${field} IS DISTINCT FROM ${add(value)}`;else if(operator==='in'){const values=value as unknown[];result=values.length?`${field} IN (${values.map(add).join(', ')})`:'FALSE';}else if(operator==='like'||operator==='ilike'||operator==='match'||operator==='imatch'){const operand=(operator==='like'||operator==='ilike')&&typeof value==='string'?value.replace(/\*/g,'%'):value,rhs=add(operand);result=`${field} ${OP[operator]} ${quantifier?`${quantifier.toUpperCase()}(${rhs})`:rhs}`;}else if(FTS[operator]){const args=config?`${add(config)}, ${add(value)}`:add(value);result=`${field} @@ ${FTS[operator]}(${args})`;}else{const rhs=add(value);result=`${field} ${OP[operator]??'='} ${quantifier?`${quantifier.toUpperCase()}(${rhs})`:rhs}`;}return negate?`NOT (${result})`:result;}
export function decodeRpcEnvelope(row:Record<string,unknown>|undefined):RpcEnvelope{if(!row)return{rows:[],count:0,affected:0};let raw=row.__pgrst_rows;if(typeof raw==='string'){try{raw=JSON.parse(raw);}catch{raw=[];}}const rows=Array.isArray(raw)?raw as Record<string,unknown>[]:[];return{rows,count:Number(row.__pgrst_count??0),affected:Number(row.__pgrst_affected??0)};}
